name: 'dnn-platform-get-version'
description: 'Fetches the latest official Dnn.Plaform release version'
inputs:
  owner:
    description: repository owner, defaults to dnnsoftware
    required: false
    default: 'dnnsoftware'
  repo:
    description: repository name, defaults to Dnn.Platform
    required: false
    default: 'Dnn.Platform'
outputs:
  version: #id of output
    description: 'The version information, contains: tag, major, minor, patch and manifestSafeVersionString'
runs:
  using: 'node12'
  main: './dist/index.js'